; AULA 1 - EXERCICIO 2
	
	ORG	0
	CLR	A		; ZERA O CONTADO
	MOV	DPTR, #1200H	; APONTA DPTR PARA 1200H
	MOV	A, #3AH		; MOVE O DADO 3AH PARA O ACUMULADOR A
	MOVX	@DPTR, A	; O DADO 3AH E ARMAZENADO NA POSICAO 1200H DA RAM EXTERNA
	CLR	A		; LIMPA O ACUMULADOR
	MOVX	A, @DPTR	; A RECEBE O VALOR ARMAZENADO NO END. APONTADO POR @DPTR
	MOV	30H, A		; NA POSICAO 30H, O CONTEUDO DE A E ARMAZENADO
	SJMP	$		; FIM DO PROGRAMA
	END
