	ORG	0

START:	MOV	DPTR, #VALUES	; MAKES DPTR POINT TO DATA POSITION OF PROGRAM MEMORY

	CLR	A		; CLEAR THE ACCUMULATOR

	; STORES IN A THE VALUE AT @DPTR
	MOVC	A, @A+DPTR	; A += THE CONTENT OF DPTR
	MOV	R0, A		; MAKES R0 = A

	CLR	A		; MAKES A = 0
	INC	DPTR		; MAKES DPTR POINT TO NEXT POSITION OF MEMORY

	; STORES IN A THE VALUE AT @DPTR
	MOVC	A, @A+DPTR	; A += THE CONTENT OF DPTR
	MOV	R1, A		; MAKES R1 = A	
	SJMP	$
	
VALUES:	DB	03AH, 0A3H
